// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: grpc/cryptomail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{0}
}

type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{1}
}

func (x *Bool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{2}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StringArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vals []string `protobuf:"bytes,1,rep,name=vals,proto3" json:"vals,omitempty"`
}

func (x *StringArray) Reset() {
	*x = StringArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArray) ProtoMessage() {}

func (x *StringArray) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArray.ProtoReflect.Descriptor instead.
func (*StringArray) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{3}
}

func (x *StringArray) GetVals() []string {
	if x != nil {
		return x.Vals
	}
	return nil
}

type Mail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From    string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To      string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Subject string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Body    string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Date    int64  `protobuf:"varint,6,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Mail) Reset() {
	*x = Mail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{4}
}

func (x *Mail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Mail) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Mail) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Mail) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Mail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Mail) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type MailArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mails []*Mail `protobuf:"bytes,1,rep,name=mails,proto3" json:"mails,omitempty"`
}

func (x *MailArray) Reset() {
	*x = MailArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailArray) ProtoMessage() {}

func (x *MailArray) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailArray.ProtoReflect.Descriptor instead.
func (*MailArray) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{5}
}

func (x *MailArray) GetMails() []*Mail {
	if x != nil {
		return x.Mails
	}
	return nil
}

type FriendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromMe bool   `protobuf:"varint,1,opt,name=fromMe,proto3" json:"fromMe,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Key    string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{6}
}

func (x *FriendRequest) GetFromMe() bool {
	if x != nil {
		return x.FromMe
	}
	return false
}

func (x *FriendRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FriendRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FriendRequestArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*FriendRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *FriendRequestArray) Reset() {
	*x = FriendRequestArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestArray) ProtoMessage() {}

func (x *FriendRequestArray) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestArray.ProtoReflect.Descriptor instead.
func (*FriendRequestArray) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{7}
}

func (x *FriendRequestArray) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type Friend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Friend) Reset() {
	*x = Friend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_cryptomail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Friend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friend) ProtoMessage() {}

func (x *Friend) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_cryptomail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friend.ProtoReflect.Descriptor instead.
func (*Friend) Descriptor() ([]byte, []int) {
	return file_grpc_cryptomail_proto_rawDescGZIP(), []int{8}
}

func (x *Friend) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Friend) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_grpc_cryptomail_proto protoreflect.FileDescriptor

var file_grpc_cryptomail_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d,
	0x61, 0x69, 0x6c, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x1c, 0x0a, 0x04, 0x42,
	0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x73, 0x22, 0x7c, 0x0a, 0x04,
	0x4d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x33, 0x0a, 0x09, 0x4d, 0x61,
	0x69, 0x6c, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d,
	0x61, 0x69, 0x6c, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22,
	0x4f, 0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x4d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x4d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x4b, 0x0a, 0x12, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x35, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x30, 0x0a,
	0x06, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32,
	0xce, 0x04, 0x0a, 0x0a, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x3a,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x10, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a,
	0x17, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x4c, 0x6f,
	0x61, 0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x10, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x22,
	0x00, 0x12, 0x3b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d,
	0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x12, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x32,
	0x0a, 0x0a, 0x49, 0x73, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x49, 0x6e, 0x12, 0x10, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x10,
	0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x42, 0x6f, 0x6f, 0x6c,
	0x22, 0x00, 0x12, 0x31, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x55, 0x52, 0x4c, 0x12, 0x10, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a,
	0x12, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0b, 0x4d, 0x61, 0x6b, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69,
	0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x10, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d,
	0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x10, 0x2e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x10, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x00,
	0x12, 0x3a, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69,
	0x6c, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x1a, 0x10, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x12, 0x10, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x4e,
	0x75, 0x6c, 0x6c, 0x1a, 0x1e, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c,
	0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x73, 0x12, 0x10, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61, 0x69, 0x6c,
	0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x17, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x6d, 0x61,
	0x69, 0x6c, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_cryptomail_proto_rawDescOnce sync.Once
	file_grpc_cryptomail_proto_rawDescData = file_grpc_cryptomail_proto_rawDesc
)

func file_grpc_cryptomail_proto_rawDescGZIP() []byte {
	file_grpc_cryptomail_proto_rawDescOnce.Do(func() {
		file_grpc_cryptomail_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_cryptomail_proto_rawDescData)
	})
	return file_grpc_cryptomail_proto_rawDescData
}

var file_grpc_cryptomail_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_grpc_cryptomail_proto_goTypes = []interface{}{
	(*Null)(nil),               // 0: cryptomail.Null
	(*Bool)(nil),               // 1: cryptomail.Bool
	(*String)(nil),             // 2: cryptomail.String
	(*StringArray)(nil),        // 3: cryptomail.StringArray
	(*Mail)(nil),               // 4: cryptomail.Mail
	(*MailArray)(nil),          // 5: cryptomail.MailArray
	(*FriendRequest)(nil),      // 6: cryptomail.FriendRequest
	(*FriendRequestArray)(nil), // 7: cryptomail.FriendRequestArray
	(*Friend)(nil),             // 8: cryptomail.Friend
}
var file_grpc_cryptomail_proto_depIdxs = []int32{
	4,  // 0: cryptomail.MailArray.mails:type_name -> cryptomail.Mail
	6,  // 1: cryptomail.FriendRequestArray.requests:type_name -> cryptomail.FriendRequest
	0,  // 2: cryptomail.CryptoMail.GetProfiles:input_type -> cryptomail.Null
	2,  // 3: cryptomail.CryptoMail.LoadProfile:input_type -> cryptomail.String
	0,  // 4: cryptomail.CryptoMail.GetCurrentProfile:input_type -> cryptomail.Null
	0,  // 5: cryptomail.CryptoMail.IsLoggedIn:input_type -> cryptomail.Null
	0,  // 6: cryptomail.CryptoMail.AuthURL:input_type -> cryptomail.Null
	0,  // 7: cryptomail.CryptoMail.MakeService:input_type -> cryptomail.Null
	0,  // 8: cryptomail.CryptoMail.RefreshMails:input_type -> cryptomail.Null
	2,  // 9: cryptomail.CryptoMail.NewFriendRequest:input_type -> cryptomail.String
	0,  // 10: cryptomail.CryptoMail.GetFriendRequests:input_type -> cryptomail.Null
	0,  // 11: cryptomail.CryptoMail.GetFriends:input_type -> cryptomail.Null
	3,  // 12: cryptomail.CryptoMail.GetProfiles:output_type -> cryptomail.StringArray
	0,  // 13: cryptomail.CryptoMail.LoadProfile:output_type -> cryptomail.Null
	2,  // 14: cryptomail.CryptoMail.GetCurrentProfile:output_type -> cryptomail.String
	1,  // 15: cryptomail.CryptoMail.IsLoggedIn:output_type -> cryptomail.Bool
	2,  // 16: cryptomail.CryptoMail.AuthURL:output_type -> cryptomail.String
	0,  // 17: cryptomail.CryptoMail.MakeService:output_type -> cryptomail.Null
	0,  // 18: cryptomail.CryptoMail.RefreshMails:output_type -> cryptomail.Null
	0,  // 19: cryptomail.CryptoMail.NewFriendRequest:output_type -> cryptomail.Null
	7,  // 20: cryptomail.CryptoMail.GetFriendRequests:output_type -> cryptomail.FriendRequestArray
	3,  // 21: cryptomail.CryptoMail.GetFriends:output_type -> cryptomail.StringArray
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_cryptomail_proto_init() }
func file_grpc_cryptomail_proto_init() {
	if File_grpc_cryptomail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_cryptomail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cryptomail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cryptomail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cryptomail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cryptomail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cryptomail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cryptomail_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cryptomail_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequestArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_cryptomail_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Friend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_cryptomail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_cryptomail_proto_goTypes,
		DependencyIndexes: file_grpc_cryptomail_proto_depIdxs,
		MessageInfos:      file_grpc_cryptomail_proto_msgTypes,
	}.Build()
	File_grpc_cryptomail_proto = out.File
	file_grpc_cryptomail_proto_rawDesc = nil
	file_grpc_cryptomail_proto_goTypes = nil
	file_grpc_cryptomail_proto_depIdxs = nil
}
